# Dockerfile to build a container with the host-check script
#
# Build:
# podman build -t host-check -f Dockerfile.host-check .
# Run (must be run with host network and mount /lib/modules):
# podman run --net host -v /lib/modules:/lib/modules host-check

FROM python:3.11-slim-bullseye

WORKDIR /app

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install procps kmod lshw

COPY scripts/host-check .

ENTRYPOINT ["./host-check_aaa"]
