[tool.black]
line-length = 79
target-version = ["py37", "py38", "py39", "py310"]
include = """
(
    \\.py$
    | scripts/xr-compose$
    | scripts/host-check$
)
"""
exclude = """
(
    Dockerfile.host-check$
)
"""

[tool.isort]
# Make compatible with Black
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
# Other options
order_by_type = true
lines_after_imports = 2
