services:
  ce1:
    xr_startup_cfg: ce1.cfg
    xr_interfaces:
      - Gi0/0/0/0

  pe1:
    xr_startup_cfg: pe1.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1

  p1:
    xr_startup_cfg: p1.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1

  pe2:
    xr_startup_cfg: pe2.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1

  ce2:
    xr_startup_cfg: ce2.cfg
    xr_interfaces:
      - Gi0/0/0/0

xr_l2networks:
  - ["ce1:Gi0/0/0/0", "pe1:Gi0/0/0/0"]
  - ["pe1:Gi0/0/0/1", "p1:Gi0/0/0/0"]
  - ["p1:Gi0/0/0/1", "pe2:Gi0/0/0/0"]
  - ["pe2:Gi0/0/0/1", "ce2:Gi0/0/0/0"]
