name: check-release
on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - "ensure-release"
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest release version
        run: |
          echo "Release version: ${{github.event.release.tag_name}}"
